# =========================================================
# TF Expression Heatmap across lineages, tissues and stages
# =========================================================
suppressPackageStartupMessages({
  library(ComplexHeatmap)
  library(circlize)
  library(stringr)
  library(grid)
})

source("heatmap_config.R")

group_avg <- read.table("Figure5G_matrix.txt", header = TRUE, row.names = 1, sep = "\t", check.names = FALSE)

existing_cols <- intersect(specified_order, colnames(group_avg))
group_avg <- as.matrix(group_avg[, existing_cols, drop = FALSE])

mat_scaled <- t(scale(t(group_avg)))
mat_scaled[is.na(mat_scaled)] <- 0

col_fun <- colorRamp2(seq(-2, 2, length.out = 100), 
                      colorRampPalette(c("#053061", "#2166AC", "#4393C3", "#92C5DE", "#D1E5F0", 
                                         "#F7F7F7", "#FDDBC7", "#F4A582", "#D6604D", "#B2182B", "#67001F"))(100))

gene_colors <- c(setNames(rep("#ba5b49", 4), c("TFDP2","KLF1","E2F7","BRCA1")),
                 setNames(rep("#c4c98a", 6), c("ZBTB18","ETS1","GATA3","TBX21","EOMES","SOX13")),
                 setNames(rep("#ae98b6", 5), c("GATA2","NFE2L2","BATF3","SNAI1","ETV5")))

info <- as.data.frame(str_split_fixed(colnames(mat_scaled), "#", 3))
colnames(info) <- c("Stage", "Tissue", "Cell type")

col_ha <- HeatmapAnnotation(
  Stage       = factor(info$Stage, levels = names(col_stage)),
  Tissue      = factor(info$Tissue, levels = names(col_tissue)),
  `Cell type` = factor(info$`Cell type`, levels = names(col_cell)),
  col = list(Tissue = col_tissue, Stage = col_stage, `Cell type` = col_cell),
  show_legend = TRUE, annotation_name_side = "left"
)

ht <- Heatmap(
  mat_scaled, name = "Zscore", col = col_fun, top_annotation = col_ha,
  cluster_rows = FALSE, cluster_columns = FALSE, column_order = colnames(mat_scaled),
  show_row_names = TRUE, show_column_names = FALSE, row_names_side = "left",
  row_names_gp = gpar(fontsize = 12, col = gene_colors[rownames(mat_scaled)]),
  border = TRUE, border_gp = gpar(col = "white", lwd = 0.1),
  width = ncol(mat_scaled) * unit(2.5, "mm"), height = nrow(mat_scaled) * unit(7, "mm")
)

pdf("Fig_Immune_heatmap.pdf", width = 18, height = 12)
draw(ht, heatmap_legend_side = "top", annotation_legend_side = "top")


boundary_genes <- c("BRCA1", "SOX13")
k <- match(boundary_genes, rownames(mat_scaled))
decorate_heatmap_body("Zscore", {
  for (i in k[!is.na(k)]) {
    y <- 1 - i / nrow(mat_scaled)
    grid.lines(x = unit(c(0, 1), "npc"), y = unit(c(y, y), "npc"), gp = gpar(col = "white", lwd = 10))
  }
})
dev.off()